---
# Those are the tasks that will prepare the Server Rest API
- name: update cache
  apt:
    update_cache: yes

- name: set jar
  copy:
    src: files/Server.jar
    dest: /etc/docker_images/Server.jar

- name: set docker file
  copy:
    src: files/Dockerfile
    dest: /etc/docker_images/Dockerfile
    
